[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP235x"
rustflags = ["-C", "link-arg=-Tdefmt.x"]

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "info"
WIFI_NETWORK = "blah"
WIFI_PASSWORD = "blah"
# WEB_SOCKET_SERVER_HOST = "192.168.49.183"
# WEB_SOCKET_SERVER_PORT = "3000"
# DEVICE_NAME = "Pico Test"
WEB_SOCKET_SERVER_HOST = "10.3.1.20"
WEB_SOCKET_SERVER_PORT = "8472"
DEVICE_NAME = "Main Space"
