[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"

[env]
ESP_LOG = "INFO"
SSID = "SSID"
PASSWORD = "PASSWORD"
NOTIFY_URL = "http://10.3.1.20:8472/"

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C", "force-frame-pointers"
]

target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
